apiVersion: v1
kind: ConfigMap
metadata:
  name: thumbnail-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  thumbnail-processing.json: |-
{{ .Files.Get "dashboards/thumbnail-processing.json" | indent 4 }}
