# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: thumbnail-proc-api
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/proxy-body-size: "25m"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: thumbnail-proc-api
#             port:
#               number: 8080
#       - path: /metrics
#         pathType: Prefix
#         backend:
#           service:
#             name: thumbnail-proc-api
#             port:
#               number: 8080
#       - path: /healthz
#         pathType: Prefix
#         backend:
#           service:
#             name: thumbnail-proc-api
#             port:
#               number: 8080
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana
#   namespace: monitoring
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /grafana(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: monitoring-grafana
#             port:
#               number: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: prometheus
#   namespace: monitoring
#   annotations:
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     nginx.ingress.kubernetes.io/use-regex: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /prometheus(/|$)(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#             name: monitoring-kube-prometheus-prometheus
#             port:
#               number: 9090
